# Generated by Django 4.2.3 on 2023-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_user.jpg', max_length=200, null=True, upload_to='profile_images/'),
        ),
    ]
