# Generated by Django 4.2.3 on 2024-01-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teska_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='main_device',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='main_organization',
        ),
    ]
