# Generated by Django 4.2.3 on 2024-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teska_main', '0002_alter_device_table_alter_organization_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineRoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_3d_view', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
