# Generated by Django 4.2.3 on 2024-01-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teska_main', '0003_engineroomfeature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngineRoomFeature',
        ),
    ]
