# Generated by Django 4.2.3 on 2024-02-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teska_main', '0006_alter_device_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100)),
                ('province', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'main_location',
                'managed': False,
            },
        ),
    ]
