# Generated by Django 4.2.3 on 2023-08-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_enginroompublicinfo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enginroom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
