# Generated by Django 4.2.3 on 2023-08-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_locationpublicinfo_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='step',
        ),
        migrations.AddField(
            model_name='enginroom',
            name='step',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
