# Generated by Django 4.2.3 on 2023-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_locationpublicinfo_step_enginroom_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginroomimage',
            name='images',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='enginroom_images/'),
        ),
    ]
