# Generated by Django 4.2.3 on 2023-08-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_enginroomimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginroomimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='enginroom_images/'),
        ),
    ]
