# Generated by Django 4.2.3 on 2023-08-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_locationpublicinfo_building_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginroomimage',
            name='enginroom',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enginroom'),
        ),
        migrations.AlterField(
            model_name='enginroompublicinfo',
            name='enginroom',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enginroom'),
        ),
        migrations.AlterField(
            model_name='installationinfo',
            name='enginroom',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enginroom'),
        ),
        migrations.AlterField(
            model_name='locationpublicinfo',
            name='enginroom',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enginroom'),
        ),
    ]
