# Generated by Django 4.2.3 on 2023-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_installationinfo_device_serial_number_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enginroomimage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='enginroompublicinfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='installationinfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='enginroom',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
