# Generated by Django 4.2.3 on 2023-09-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_enginroom_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enginroomimage',
            old_name='images',
            new_name='image',
        ),
    ]
