# Generated by Django 4.2.3 on 2024-02-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhistory',
            name='device',
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='text',
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='user',
        ),
    ]
