# Generated by Django 4.2.3 on 2024-02-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eventhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='province',
        ),
    ]
