# Generated by Django 4.2.3 on 2023-09-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_locationpublicinfo_city_locationpublicinfo_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationinfo',
            name='device_serial_number_image',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='device_serial_number_images/'),
        ),
    ]
