# Generated by Django 4.2.3 on 2023-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_enginroomimage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginroom',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
