# Generated by Django 4.2.3 on 2023-11-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_installationinfo_device_serial_number_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enginroomimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='enginroompublicinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='installationinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='locationpublicinfo',
            options={'ordering': ['-id']},
        ),
    ]
