# Generated by Django 4.2.3 on 2024-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_eventhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='enginroomimage',
            name='enginroom',
        ),
        migrations.RemoveField(
            model_name='enginroompublicinfo',
            name='enginroom',
        ),
        migrations.RemoveField(
            model_name='eventhistory',
            name='enginroom',
        ),
        migrations.RemoveField(
            model_name='installationinfo',
            name='enginroom',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='enginroom',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locationpublicinfo',
            name='province',
        ),
        migrations.AddField(
            model_name='enginroomimage',
            name='device',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='enginroompublicinfo',
            name='device',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='enginroompublicinfo',
            name='serial_number',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='device',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='installationinfo',
            name='device',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='installationinfo',
            name='serial_number',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='locationpublicinfo',
            name='device',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='locationpublicinfo',
            name='linker_person1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locationpublicinfo',
            name='linker_person2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locationpublicinfo',
            name='serial_number',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='enginroomimage',
            name='user',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='enginroompublicinfo',
            name='user',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='user',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='installationinfo',
            name='user',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='locationpublicinfo',
            name='user',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Enginroom',
        ),
    ]
