# Generated by Django 4.2.3 on 2023-08-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_enginroompublicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginroompublicinfo',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='enginroompublicinfo',
            name='usage',
            field=models.CharField(choices=[('heating', 'گرمایشی'), ('sanitary', 'آبگرم بهداشتی'), ('both', 'هردو')], max_length=2000),
        ),
    ]
