# Generated by Django 4.2.3 on 2023-08-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_organization_enginroom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enginroompublicinfo',
            old_name='organization',
            new_name='enginroom',
        ),
        migrations.RenameField(
            model_name='locationpublicinfo',
            old_name='organization',
            new_name='enginroom',
        ),
    ]
