# Generated by Django 4.2.3 on 2023-08-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_enginroomimage_enginroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationinfo',
            name='device_serial_number_image',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to='device_serial_number/'),
        ),
        migrations.AlterField(
            model_name='locationpublicinfo',
            name='building_image',
            field=models.ImageField(blank=True, default='no-image.jpg', max_length=200, null=True, upload_to='building_images/'),
        ),
    ]
