# Generated by Django 4.2.3 on 2023-09-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='added_by',
            new_name='owner',
        ),
    ]
