"""
Django settings for installersProject project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')
PWA_APP_NAME = 'Shouka'
PWA_APP_DESCRIPTION = "Application for Hirkan Installers"
PWA_APP_THEME_COLOR = '#000000'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': 'static/images/logo-160x160.png',
        'sizes': '160x160',
    },
    {
        'src': 'static/images/logo-57x57.png',
        'sizes': '57x57',
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': 'static/images/logo-160x160.png',
        'sizes': '160x160'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': 'static/images/logo.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'rtl'
PWA_APP_LANG = 'en-US'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!$p0okr*b5(+d!)1-f)vu4m%f%ep63&+9y*1vwz2po6_t55u#l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

ADMIN_URL = 'h7069hats3x829th'

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
# SESSION_COOKIE_AGE = 5 * 60
# Application definition
APPEND_SLASH = False

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 10  


################################# API FROM TESKA #####################################
API_URL = 'https://teska.romaksystem.com/api/v2/objects/add'
EDIT_API_URL = 'https://teska.romaksystem.com/api/v2/objects/edit'
ADD_DEVICES_URL = 'https://teska.romaksystem.com/api/v2/devices/add' 
EDIT_DEVICES_URL = 'https://teska.romaksystem.com/api/v2/devices/edit'
API_KEY = 'Rl9IDc9c.SeThcnpzSJHpAti2p277R8YnP4ao5l5i'
######################################################################################

API_V2_SECRETS = {
    'AES_SECRET_KEY': 'XkBrelg5SlE3az9ORzkrbXY4U1ZUeFU5NWt6WnA1cHE=',
    'AES_IV': 'OVFSKzNfYz8zM25lczQtRQ==',
}


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',

    'users.apps.UsersConfig',
    'api.apps.ApiConfig',
    'frontend.apps.FrontendConfig',
    'main.apps.MainConfig',
    'teska_main.apps.TeskaMainConfig',
    'apiv2.apps.Apiv2Config',
    'pwa',

]

# # Simplified static file serving.
# # https://warehouse.python.org/project/whitenoise/
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.CustomUserPagination',
    'PAGE_SIZE': 10,
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
    'MAX_PAGE_SIZE': 100,
    }

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'installersProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'installersProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASE_ROUTERS = ['teska_main.routers.teskaServer']
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'shoukadb',
        'USER': 'postgres',
        'PASSWORD': 'C3]9Q?0VUt',
        'HOST': 'localhost',
        'PORT': ''
    },
    'teska_server': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'teskadb',
        'USER': 'shouka',
        'PASSWORD': 'SHK@teska#110',
        # Port forward
        'HOST': '2.181.78.120',
        'PORT': '15432',

        # Local
        # 'HOST': '192.168.1.205',
        # 'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


CORS_ALLOW_ALL_ORIGINS = True
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#SESSION_SAVE_EVERY_REQUEST = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
#STATICFILES_DIRS = [
#    BASE_DIR / 'static'
#]
MEDIA_ROOT = '/home/installersProject/media'
# DEPLOY 
STATIC_ROOT = '/home/installersProject/static'
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING_PATH = "/home/installersProject/logs/"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s]  %(message)s",
            'datefmt': "[%Y-%m-%d %H:%M:%S]"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': f'{LOGGING_PATH}/Shouka_app.log',
            'when': 'midnight',  
            'backupCount': 365,  
            'formatter': 'verbose',
        },

    },
    'loggers': {
        'root': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

